### ISSUE TITLE
scope matched would be override word-completions

### ISSUE THREAD

**Issue by songtm** [waqiju/UnityShaderST3#1]
Hi, I used your plugin, it's awesome, but there is a small problem.
Detail describption at  https://github.com/Pleasurazy/Sublime-Better-Completion.
Or you can just keep  the .sublime-snippet file way as "cjsjy123/Unity-Shader"

**Comment by waqiju** [comment]
Thanks for your feedback.
The problem is the content in '*.sublime-complections' override the default auto-completions of sublime. And it is a obstacle of happy coding actually -_-

Using 'Sublime-Better_Completion' or '*.sublime_snippet' seems can solve the problem, but I still wonder a better way to re-design the function of code completion.
Currently, I am busy with the upcoming version(0.3.0). The problem maybe solved in version between 0.3.1 with 0.4.0 .
