### ISSUE TITLE
Plugin gives warning that version is wrong, but the folder is correct?

### ISSUE THREAD

**Issue by ninja542** [waqiju/UnityShaderST3#7]
Hi everyone, I keep getting warnings that the version is wrong?

Here's the picture of the warning:
![image](https://user-images.githubusercontent.com/18501292/92624676-c822e380-f295-11ea-8495-41ddfa43d004.png)

Here's the default settings and the package folder
![image](https://user-images.githubusercontent.com/18501292/92624565-a6296100-f295-11ea-8616-2d0861dc36ad.png)

**Comment by guigui17f** [comment]
> Hi everyone, I keep getting warnings that the version is wrong?
> 
> Here's the picture of the warning:
> ![image](https://user-images.githubusercontent.com/18501292/92624676-c822e380-f295-11ea-8495-41ddfa43d004.png)
> 
> Here's the default settings and the package folder
> ![image](https://user-images.githubusercontent.com/18501292/92624565-a6296100-f295-11ea-8616-2d0861dc36ad.png)

I got the same problem and finally solved it by myself.
In the plugin floder (C:\Users\ [UserName] \AppData\Roaming\Sublime Text 3\Packages\Unity Shader) there's a setting file naming "UnityShader.sublime-settings", but in the plugin code file (UnityShader.py) there are some codes like:
sublime.load_settings("Unity Shader.sublime-settings")
There's an extra white space between "Unity" and "Shader", so just delete the white space in every string like this will solve this problem.
Hoping the developer fix this soon...

**Comment by waqiju** [comment]
Sorry for that. 
It is a mistake in development. I not discover it in my develpment enviorment, because the threre already is a file which named "Unity Shader.sublime-setting" (with WHITESPACE in file name)  in [Packages/User] folder. Then it seems to work well and I didn't discover the mistake.

Finally, thanks for @ninja542  and @guigui17f . I see the issue just now, and it has fixed. Welcome to feedback any problem.
